### ISSUE TITLE
error: ‘CLOCK_MONOTONIC’ was not declared in this scope

### ISSUE THREAD

**Issue by garethharding** [a1k0n/a1gpt#1]
If anyone is having this issue I fixed it by adding:

`#include <time.h>`

to main.cpp.

**Comment by garethharding** [comment]
...

**Comment by a1k0n** [comment]
you're right, that should have always been there. Added, thanks!

**Comment by garethharding** [comment]
Thanks for your work, looking to forward to trying this!
